import { Block, TextBlock, ImageBlock, ShapeBlock } from "@/store/useEditorStore";
import { CANVAS_WIDTH, CANVAS_HEIGHT } from "@/lib/constants/canvas";

export type SlideTemplateId =
  | "title_slide"
  | "title_subtitle"
  | "welcome_slide"
  | "one_column"
  | "two_columns"
  | "three_columns"
  | "text_image_left"
  | "text_image_right"
  | "full_image"
  | "quote_citation"
  | "statistics_big"
  | "comparison_two"
  | "comparison_three"
  | "process_steps"
  | "quiz_intro"
  | "knowledge_check"
  | "activity_description"
  | "thank_you"
  | "summary"
  | "call_to_action"
  | "contact_info";

export interface SlideTemplate {
  id: SlideTemplateId;
  name: string;
  description: string;
  category: "abertura" | "conteudo" | "dados" | "interativo" | "encerramento";
  thumbnail: string;
  generateBlocks: () => Block[];
}

const createDefaultTextProps = (): Omit<TextBlock, "id" | "type" | "x" | "y" | "width" | "height" | "content"> => ({
  fontSize: 20,
  fontWeight: "400",
  fontStyle: "normal",
  textDecorationLine: "none",
  color: "#333333",
  textAlign: "left",
  lineHeight: 1.5,
  letterSpacing: 0,
  textShadow: "none",
  backgroundColor: "transparent",
  borderRadius: 0,
  opacity: 1,
  listType: "none",
  zIndex: 10,
});

const createDefaultImageProps = (): Omit<ImageBlock, "id" | "type" | "x" | "y" | "width" | "height"> => ({
  src: "https://images.unsplash.com/photo-1557683316-973673baf926?q=80&w=600&auto=format&fit=crop",
  alt: "Template Image",
  objectFit: "cover",
  opacity: 1,
  borderRadius: 8,
  borderWidth: 0,
  borderColor: "#000000",
  boxShadow: "none",
  zIndex: 10,
});

const createDefaultShapeProps = (): Omit<ShapeBlock, "id" | "type" | "x" | "y" | "width" | "height"> => ({
  shapeType: "rectangle",
  fillColor: "#6366f1",
  strokeColor: "transparent",
  strokeWidth: 0,
  opacity: 1,
  rotation: 0,
  zIndex: 5,
});

export const SLIDE_TEMPLATES: SlideTemplate[] = [
  // === ABERTURA (OPENING) ===
  {
    id: "title_slide",
    name: "Slide de Título",
    description: "Ideal para iniciar um módulo com título de impacto e acento visual.",
    category: "abertura",
    thumbnail: "📌",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#f8f9ff",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: 120,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 180,
        width: 840,
        height: 100,
        content: "<p>Título Principal do Módulo</p>",
        ...createDefaultTextProps(),
        fontSize: 56,
        fontWeight: "700",
        color: "#1e293b",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 300,
        width: 840,
        height: 60,
        content: "<p>Breve descrição ou subtítulo apresentando o objetivo deste módulo.</p>",
        ...createDefaultTextProps(),
        fontSize: 20,
        color: "#64748b",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "title_subtitle",
    name: "Título + Subtítulo",
    description: "Variação clássica com título e subtítulo em destaque sobre fundo claro.",
    category: "abertura",
    thumbnail: "✨",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 150,
        width: 800,
        height: 80,
        content: "<p>Título da Apresentação</p>",
        ...createDefaultTextProps(),
        fontSize: 60,
        fontWeight: "800",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 260,
        width: 800,
        height: 50,
        content: "<p>Subtítulo ou descrição breve do conteúdo principal</p>",
        ...createDefaultTextProps(),
        fontSize: 24,
        color: "#6366f1",
        textAlign: "center",
        fontWeight: "600",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 400,
        y: 330,
        width: 160,
        height: 3,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 10,
      } as ShapeBlock,
    ],
  },
  {
    id: "welcome_slide",
    name: "Slide de Boas-vindas",
    description: "Acolhedor com imagem grande e mensagem de bem-vindo.",
    category: "abertura",
    thumbnail: "🎉",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "image",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultImageProps(),
        opacity: 0.5,
        zIndex: 1,
      } as ImageBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "rgba(255, 255, 255, 0.85)",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 180,
        width: 760,
        height: 120,
        content: "<p>Bem-vindo ao Curso!</p>",
        ...createDefaultTextProps(),
        fontSize: 52,
        fontWeight: "700",
        color: "#6366f1",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 320,
        width: 760,
        height: 60,
        content: "<p>Prepare-se para uma experiência de aprendizado transformadora</p>",
        ...createDefaultTextProps(),
        fontSize: 20,
        color: "#475569",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
    ],
  },

  // === CONTEÚDO (CONTENT) ===
  {
    id: "one_column",
    name: "Uma Coluna",
    description: "Layout simples com título e conteúdo em coluna única.",
    category: "conteudo",
    thumbnail: "📝",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 60,
        content: "<p>Tópico Principal</p>",
        ...createDefaultTextProps(),
        fontSize: 44,
        fontWeight: "700",
        color: "#0f172a",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 60,
        y: 110,
        width: 100,
        height: 4,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 10,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 140,
        width: 840,
        height: 370,
        content: "<p>Descreva o conteúdo principal aqui. Use esta seção para apresentar informações importantes, conceitos-chave e explicações detalhadas. O layout em coluna única é perfeito para leitura linear e focada.</p><p><br></p><ul><li>Ponto importante número um</li><li>Ponto importante número dois</li><li>Ponto importante número três</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 18,
        color: "#475569",
        lineHeight: 1.8,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "two_columns",
    name: "Duas Colunas",
    description: "Comparação lado a lado ou conteúdo paralelo.",
    category: "conteudo",
    thumbnail: "⬌",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 50,
        content: "<p>Comparação ou Dois Tópicos</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 60,
        y: 100,
        width: 840,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#e2e8f0",
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 130,
        width: 380,
        height: 360,
        content: "<p><strong>Coluna 1</strong></p><p><br></p><p>Conteúdo da primeira coluna. Descreva o primeiro tópico, conceito ou abordagem aqui.</p><ul><li>Benefício 1</li><li>Benefício 2</li><li>Benefício 3</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        lineHeight: 1.6,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 520,
        y: 130,
        width: 380,
        height: 360,
        content: "<p><strong>Coluna 2</strong></p><p><br></p><p>Conteúdo da segunda coluna. Descreva o segundo tópico, conceito ou abordagem aqui.</p><ul><li>Vantagem 1</li><li>Vantagem 2</li><li>Vantagem 3</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        lineHeight: 1.6,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "three_columns",
    name: "Três Colunas",
    description: "Layout para apresentar três elementos em paralelo.",
    category: "conteudo",
    thumbnail: "≡",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 50,
        content: "<p>Três Perspectivas</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 120,
        width: 260,
        height: 370,
        content: "<p><strong>Opção 1</strong></p><p><br></p><p>Conteúdo conciso para a primeira perspectiva ou elemento.</p><p><br></p><ul><li>Item</li><li>Item</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#475569",
        lineHeight: 1.6,
        backgroundColor: "#f8fafc",
        borderRadius: 8,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 350,
        y: 120,
        width: 260,
        height: 370,
        content: "<p><strong>Opção 2</strong></p><p><br></p><p>Conteúdo conciso para a segunda perspectiva ou elemento.</p><p><br></p><ul><li>Item</li><li>Item</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#475569",
        lineHeight: 1.6,
        backgroundColor: "#f1f5f9",
        borderRadius: 8,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 640,
        y: 120,
        width: 260,
        height: 370,
        content: "<p><strong>Opção 3</strong></p><p><br></p><p>Conteúdo conciso para a terceira perspectiva ou elemento.</p><p><br></p><ul><li>Item</li><li>Item</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#475569",
        lineHeight: 1.6,
        backgroundColor: "#f8fafc",
        borderRadius: 8,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "text_image_left",
    name: "Imagem à Esquerda",
    description: "Imagem grande à esquerda com conteúdo de texto à direita.",
    category: "conteudo",
    thumbnail: "🖼️",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "image",
        x: 0,
        y: 0,
        width: 450,
        height: CANVAS_HEIGHT,
        ...createDefaultImageProps(),
        borderRadius: 0,
        zIndex: 5,
      } as ImageBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 480,
        y: 50,
        width: 420,
        height: 60,
        content: "<p>Título do Conteúdo</p>",
        ...createDefaultTextProps(),
        fontSize: 36,
        fontWeight: "700",
        color: "#0f172a",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 480,
        y: 130,
        width: 420,
        height: 370,
        content: "<p>Adicione uma descrição detalhada ao lado da imagem. Este layout é perfeito para explicações visuais acompanhadas de contexto textual.</p><p><br></p><ul><li>Ponto de aprendizado 1</li><li>Ponto de aprendizado 2</li><li>Ponto de aprendizado 3</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        lineHeight: 1.7,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "text_image_right",
    name: "Imagem à Direita",
    description: "Conteúdo de texto à esquerda com imagem grande à direita.",
    category: "conteudo",
    thumbnail: "📸",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 50,
        width: 420,
        height: 60,
        content: "<p>Título do Conteúdo</p>",
        ...createDefaultTextProps(),
        fontSize: 36,
        fontWeight: "700",
        color: "#0f172a",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 130,
        width: 420,
        height: 370,
        content: "<p>Adicione uma descrição detalhada ao lado da imagem. Este layout é perfeito para explicações visuais acompanhadas de contexto textual.</p><p><br></p><ul><li>Ponto de aprendizado 1</li><li>Ponto de aprendizado 2</li><li>Ponto de aprendizado 3</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        lineHeight: 1.7,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "image",
        x: 510,
        y: 0,
        width: 450,
        height: CANVAS_HEIGHT,
        ...createDefaultImageProps(),
        borderRadius: 0,
        zIndex: 5,
      } as ImageBlock,
    ],
  },
  {
    id: "full_image",
    name: "Imagem Full Screen",
    description: "Imagem em tela cheia com texto superposto.",
    category: "conteudo",
    thumbnail: "🌅",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "image",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultImageProps(),
        borderRadius: 0,
        zIndex: 1,
      } as ImageBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 300,
        width: CANVAS_WIDTH,
        height: 240,
        ...createDefaultShapeProps(),
        fillColor: "rgba(0, 0, 0, 0.5)",
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 320,
        width: 800,
        height: 60,
        content: "<p>Texto sobre a Imagem</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#ffffff",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 400,
        width: 800,
        height: 50,
        content: "<p>Descrição ou contexto adicional sobre a imagem</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#e2e8f0",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "quote_citation",
    name: "Citação/Quote",
    description: "Destaca uma citação ou frase inspiradora.",
    category: "conteudo",
    thumbnail: "💬",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#f0f4ff",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 60,
        y: 140,
        width: 6,
        height: 260,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 160,
        width: 760,
        height: 220,
        content: "<p>&quot;Uma citação poderosa ou frase inspiradora que destaca um conceito-chave do aprendizado. Use esta seção para enfatizar ideias importantes e gerar reflexão.&quot;</p>",
        ...createDefaultTextProps(),
        fontSize: 32,
        fontWeight: "600",
        color: "#1e293b",
        textAlign: "left",
        lineHeight: 1.8,
        fontStyle: "italic",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 410,
        width: 760,
        height: 40,
        content: "<p>— Nome do Autor ou Fonte</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#6366f1",
        fontWeight: "600",
        zIndex: 10,
      } as TextBlock,
    ],
  },

  // === DADOS (DATA) ===
  {
    id: "statistics_big",
    name: "Estatísticas em Destaque",
    description: "Exibe números grandes com contexto para dados importantes.",
    category: "dados",
    thumbnail: "📊",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 30,
        width: 840,
        height: 50,
        content: "<p>Números que Importam</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 140,
        width: 240,
        height: 280,
        content: "<p style='font-size: 56px; font-weight: 800; color: #6366f1; text-align: center; margin: 0;'>85%</p><p style='text-align: center; margin-top: 10px;'>Métrica de Sucesso</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        textAlign: "center",
        lineHeight: 1.6,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 360,
        y: 140,
        width: 240,
        height: 280,
        content: "<p style='font-size: 56px; font-weight: 800; color: #8b5cf6; text-align: center; margin: 0;'>2.5M</p><p style='text-align: center; margin-top: 10px;'>Usuários Ativos</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        textAlign: "center",
        lineHeight: 1.6,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 640,
        y: 140,
        width: 240,
        height: 280,
        content: "<p style='font-size: 56px; font-weight: 800; color: #ec4899; text-align: center; margin: 0;'>24h</p><p style='text-align: center; margin-top: 10px;'>Tempo Médio</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        textAlign: "center",
        lineHeight: 1.6,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "comparison_two",
    name: "Comparação Dupla",
    description: "Compara dois elementos com ícones e descrições.",
    category: "dados",
    thumbnail: "⚖️",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 30,
        width: 840,
        height: 50,
        content: "<p>Análise Comparativa</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 80,
        y: 120,
        width: 380,
        height: 380,
        ...createDefaultShapeProps(),
        fillColor: "#eff6ff",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 140,
        width: 340,
        height: 40,
        content: "<p style='text-align: center; font-size: 28px; font-weight: 700; color: #0369a1;'>Opção A</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#0369a1",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 200,
        width: 340,
        height: 280,
        content: "<p><strong>Características:</strong></p><ul><li>Benefício 1</li><li>Benefício 2</li><li>Benefício 3</li><li>Benefício 4</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        lineHeight: 1.8,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 500,
        y: 120,
        width: 380,
        height: 380,
        ...createDefaultShapeProps(),
        fillColor: "#fef3c7",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 520,
        y: 140,
        width: 340,
        height: 40,
        content: "<p style='text-align: center; font-size: 28px; font-weight: 700; color: #b45309;'>Opção B</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#b45309",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 520,
        y: 200,
        width: 340,
        height: 280,
        content: "<p><strong>Características:</strong></p><ul><li>Vantagem 1</li><li>Vantagem 2</li><li>Vantagem 3</li><li>Vantagem 4</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        lineHeight: 1.8,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "comparison_three",
    name: "Comparação Tripla",
    description: "Compara três elementos em colunas paralelas.",
    category: "dados",
    thumbnail: "🔀",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 20,
        width: 840,
        height: 40,
        content: "<p>Análise Comparativa</p>",
        ...createDefaultTextProps(),
        fontSize: 36,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 60,
        y: 90,
        width: 270,
        height: 420,
        ...createDefaultShapeProps(),
        fillColor: "#dbeafe",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 75,
        y: 110,
        width: 240,
        height: 35,
        content: "<p style='text-align: center; font-weight: 700; font-size: 18px; color: #0369a1;'>Opção 1</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 75,
        y: 160,
        width: 240,
        height: 330,
        content: "<ul><li>Recurso 1</li><li>Recurso 2</li><li>Recurso 3</li><li>Recurso 4</li></ul><p style='margin-top: 20px; text-align: center;'><strong>Custo:</strong> Médio</p>",
        ...createDefaultTextProps(),
        fontSize: 13,
        color: "#1e293b",
        lineHeight: 1.7,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 360,
        y: 90,
        width: 270,
        height: 420,
        ...createDefaultShapeProps(),
        fillColor: "#fde047",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 375,
        y: 110,
        width: 240,
        height: 35,
        content: "<p style='text-align: center; font-weight: 700; font-size: 18px; color: #b45309;'>Opção 2</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 375,
        y: 160,
        width: 240,
        height: 330,
        content: "<ul><li>Recurso 1</li><li>Recurso 2</li><li>Recurso 3</li><li>Recurso 4</li></ul><p style='margin-top: 20px; text-align: center;'><strong>Custo:</strong> Alto</p>",
        ...createDefaultTextProps(),
        fontSize: 13,
        color: "#1e293b",
        lineHeight: 1.7,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 660,
        y: 90,
        width: 270,
        height: 420,
        ...createDefaultShapeProps(),
        fillColor: "#d1d5db",
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 675,
        y: 110,
        width: 240,
        height: 35,
        content: "<p style='text-align: center; font-weight: 700; font-size: 18px; color: #374151;'>Opção 3</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 675,
        y: 160,
        width: 240,
        height: 330,
        content: "<ul><li>Recurso 1</li><li>Recurso 2</li><li>Recurso 3</li><li>Recurso 4</li></ul><p style='margin-top: 20px; text-align: center;'><strong>Custo:</strong> Baixo</p>",
        ...createDefaultTextProps(),
        fontSize: 13,
        color: "#1e293b",
        lineHeight: 1.7,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "process_steps",
    name: "Passos do Processo",
    description: "Mostra um processo em etapas sequenciais.",
    category: "dados",
    thumbnail: "📋",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 30,
        width: 840,
        height: 50,
        content: "<p>Processo em Etapas</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      // Step 1
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 80,
        y: 140,
        width: 60,
        height: 60,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        borderRadius: 30,
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 95,
        y: 150,
        width: 30,
        height: 40,
        content: "<p style='text-align: center; font-weight: 800; font-size: 24px; color: white;'>1</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 220,
        width: 120,
        height: 80,
        content: "<p style='text-align: center; font-weight: 600;'>Etapa Um</p><p style='text-align: center; font-size: 13px;'>Descrição breve</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        zIndex: 10,
      } as TextBlock,
      // Step 2
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 280,
        y: 140,
        width: 60,
        height: 60,
        ...createDefaultShapeProps(),
        fillColor: "#8b5cf6",
        borderRadius: 30,
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 295,
        y: 150,
        width: 30,
        height: 40,
        content: "<p style='text-align: center; font-weight: 800; font-size: 24px; color: white;'>2</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 260,
        y: 220,
        width: 120,
        height: 80,
        content: "<p style='text-align: center; font-weight: 600;'>Etapa Dois</p><p style='text-align: center; font-size: 13px;'>Descrição breve</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        zIndex: 10,
      } as TextBlock,
      // Arrow 1-2
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 160,
        y: 165,
        width: 100,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#cbd5e1",
        zIndex: 3,
      } as ShapeBlock,
      // Step 3
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 480,
        y: 140,
        width: 60,
        height: 60,
        ...createDefaultShapeProps(),
        fillColor: "#ec4899",
        borderRadius: 30,
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 495,
        y: 150,
        width: 30,
        height: 40,
        content: "<p style='text-align: center; font-weight: 800; font-size: 24px; color: white;'>3</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 460,
        y: 220,
        width: 120,
        height: 80,
        content: "<p style='text-align: center; font-weight: 600;'>Etapa Três</p><p style='text-align: center; font-size: 13px;'>Descrição breve</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        zIndex: 10,
      } as TextBlock,
      // Arrow 2-3
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 360,
        y: 165,
        width: 100,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#cbd5e1",
        zIndex: 3,
      } as ShapeBlock,
      // Step 4
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 680,
        y: 140,
        width: 60,
        height: 60,
        ...createDefaultShapeProps(),
        fillColor: "#f59e0b",
        borderRadius: 30,
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 695,
        y: 150,
        width: 30,
        height: 40,
        content: "<p style='text-align: center; font-weight: 800; font-size: 24px; color: white;'>4</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 660,
        y: 220,
        width: 120,
        height: 80,
        content: "<p style='text-align: center; font-weight: 600;'>Etapa Quatro</p><p style='text-align: center; font-size: 13px;'>Descrição breve</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#1e293b",
        zIndex: 10,
      } as TextBlock,
      // Arrow 3-4
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 560,
        y: 165,
        width: 100,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#cbd5e1",
        zIndex: 3,
      } as ShapeBlock,
    ],
  },

  // === INTERATIVO (INTERACTIVE) ===
  {
    id: "quiz_intro",
    name: "Introdução Quiz",
    description: "Slide de introdução para uma seção de quiz interativa.",
    category: "interativo",
    thumbnail: "❓",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#fef3c7",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 100,
        width: 800,
        height: 80,
        content: "<p style='font-size: 64px; text-align: center;'>🎯</p>",
        ...createDefaultTextProps(),
        fontSize: 16,
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 190,
        width: 800,
        height: 80,
        content: "<p>Vamos Testar Seu Conhecimento!</p>",
        ...createDefaultTextProps(),
        fontSize: 44,
        fontWeight: "700",
        color: "#92400e",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 310,
        width: 760,
        height: 150,
        content: "<p>Você vai responder a uma série de perguntas para consolidar seu aprendizado. Teste seus conhecimentos e veja como está progredindo neste tema.</p>",
        ...createDefaultTextProps(),
        fontSize: 20,
        color: "#b45309",
        textAlign: "center",
        lineHeight: 1.8,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "knowledge_check",
    name: "Verificação de Conhecimento",
    description: "Slide para checar compreensão de um conceito.",
    category: "interativo",
    thumbnail: "✅",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#f0fdf4",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 60,
        content: "<p>Você Compreendeu?</p>",
        ...createDefaultTextProps(),
        fontSize: 40,
        fontWeight: "700",
        color: "#166534",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 140,
        y: 130,
        width: 680,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#22c55e",
        zIndex: 3,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 180,
        width: 800,
        height: 250,
        content: "<p style='font-size: 24px; font-weight: 600; margin-bottom: 30px;'>Qual das seguintes afirmações é correta?</p><ul style='font-size: 18px; line-height: 2.2;'><li>Opção A</li><li>Opção B</li><li>Opção C</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#166534",
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "activity_description",
    name: "Descrição de Atividade",
    description: "Apresenta uma atividade prática para os alunos.",
    category: "interativo",
    thumbnail: "🎬",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#dbeafe",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 70,
        content: "<p>Atividade Prática</p>",
        ...createDefaultTextProps(),
        fontSize: 44,
        fontWeight: "700",
        color: "#0369a1",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 120,
        y: 130,
        width: 720,
        height: 300,
        ...createDefaultShapeProps(),
        fillColor: "#ffffff",
        borderRadius: 12,
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 140,
        y: 150,
        width: 680,
        height: 260,
        content: "<p style='font-weight: 600; font-size: 20px; color: #0369a1; margin-bottom: 15px;'>O que você precisa fazer:</p><ol style='font-size: 16px; line-height: 2;'><li>Primeiro passo da atividade</li><li>Segundo passo da atividade</li><li>Terceiro passo da atividade</li><li>Envie ou compartilhe seu resultado</li></ol>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#0c4a6e",
        zIndex: 10,
      } as TextBlock,
    ],
  },

  // === ENCERRAMENTO (CLOSING) ===
  {
    id: "thank_you",
    name: "Obrigado",
    description: "Slide de agradecimento e conclusão.",
    category: "encerramento",
    thumbnail: "🙏",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#0f172a",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 160,
        width: 800,
        height: 100,
        content: "<p>Obrigado!</p>",
        ...createDefaultTextProps(),
        fontSize: 64,
        fontWeight: "800",
        color: "#ffffff",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 180,
        y: 280,
        width: 600,
        height: 50,
        content: "<p>Você completou este módulo de aprendizado</p>",
        ...createDefaultTextProps(),
        fontSize: 24,
        color: "#94a3b8",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 400,
        y: 350,
        width: 160,
        height: 3,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 10,
      } as ShapeBlock,
    ],
  },
  {
    id: "summary",
    name: "Resumo",
    description: "Resume os pontos-chave aprendidos.",
    category: "encerramento",
    thumbnail: "📌",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 40,
        width: 840,
        height: 60,
        content: "<p>Resumo de Aprendizado</p>",
        ...createDefaultTextProps(),
        fontSize: 44,
        fontWeight: "700",
        color: "#0f172a",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 60,
        y: 110,
        width: 840,
        height: 2,
        ...createDefaultShapeProps(),
        fillColor: "#6366f1",
        zIndex: 5,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 150,
        width: 760,
        height: 340,
        content: "<p style='font-weight: 600; font-size: 18px; margin-bottom: 20px;'>Principais Conceitos:</p><ul style='font-size: 18px; line-height: 2;'><li>Conceito importante 1 - Base do aprendizado</li><li>Conceito importante 2 - Aplicação prática</li><li>Conceito importante 3 - Desenvolvimento</li><li>Conceito importante 4 - Consolidação</li></ul>",
        ...createDefaultTextProps(),
        fontSize: 16,
        color: "#475569",
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "call_to_action",
    name: "Call to Action",
    description: "Motiva a próxima ação ou desafio.",
    category: "encerramento",
    thumbnail: "🚀",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 80,
        y: 120,
        width: 800,
        height: 100,
        content: "<p>Próximo Desafio</p>",
        ...createDefaultTextProps(),
        fontSize: 52,
        fontWeight: "800",
        color: "#ffffff",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 100,
        y: 250,
        width: 760,
        height: 200,
        content: "<p style='font-size: 24px; margin-bottom: 30px;'>Está pronto para continuar?</p><p>Avance para o próximo módulo e coloque em prática tudo o que aprendeu. Seu progresso é importante!</p>",
        ...createDefaultTextProps(),
        fontSize: 18,
        color: "#f1f5f9",
        textAlign: "center",
        lineHeight: 1.8,
        zIndex: 10,
      } as TextBlock,
    ],
  },
  {
    id: "contact_info",
    name: "Informações de Contato",
    description: "Apresenta informações de contato e suporte.",
    category: "encerramento",
    thumbnail: "📧",
    generateBlocks: () => [
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 0,
        y: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        ...createDefaultShapeProps(),
        fillColor: "#f8fafc",
        zIndex: 1,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 60,
        y: 50,
        width: 840,
        height: 60,
        content: "<p>Fique em Contato</p>",
        ...createDefaultTextProps(),
        fontSize: 44,
        fontWeight: "700",
        color: "#0f172a",
        textAlign: "center",
        zIndex: 10,
      } as TextBlock,
      {
        id: crypto.randomUUID(),
        type: "shape",
        x: 200,
        y: 140,
        width: 560,
        height: 320,
        ...createDefaultShapeProps(),
        fillColor: "#ffffff",
        borderRadius: 12,
        zIndex: 2,
      } as ShapeBlock,
      {
        id: crypto.randomUUID(),
        type: "text",
        x: 240,
        y: 170,
        width: 480,
        height: 260,
        content: "<p style='text-align: center; font-weight: 600; font-size: 20px; margin-bottom: 25px; color: #6366f1;'>Entre em Contato</p><p style='font-size: 16px; margin: 15px 0;'><strong>Email:</strong> seu@email.com</p><p style='font-size: 16px; margin: 15px 0;'><strong>Telefone:</strong> (11) 9999-9999</p><p style='font-size: 16px; margin: 15px 0;'><strong>Website:</strong> www.seusite.com</p><p style='font-size: 14px; margin-top: 30px; color: #64748b;'>Disponível para dúvidas e suporte</p>",
        ...createDefaultTextProps(),
        fontSize: 14,
        color: "#475569",
        zIndex: 10,
      } as TextBlock,
    ],
  },
];
